### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by zorro8003PL** [Thefilippop1PL/Bazzars#11]
Jak tworze bazar to nie pojawia się hologram, i jak klikam na gracza prawym to nic się nie dzieje.
Mam silnik spigot 1.7.10

**Comment by Thefilippop1PL** [comment]
Podaj logi i wersje pluginu.

**Comment by zorro8003PL** [comment]
Wersja najnowsza (czyli v1.3)
Logi ze startu: http://pastebin.com/jxznyAFg

**Comment by Thefilippop1PL** [comment]
a przy tworzeniu/klikaniu?

**Comment by zorro8003PL** [comment]
Nic nie pokazuję sie w konsoli, poprostu nic się nie dzieje xd

**Comment by Thefilippop1PL** [comment]
Jakie komendy wpisujesz do tworzenia bazarow? '/bazar stworz' przygotowywuje tylko twoj bazar, abys mogl dodawac przedmioty do niego, a potem dopiero wpisujesz '/bazar otworz'.

**Comment by zorro8003PL** [comment]
A no tak dzięki! Działa już wszystko.
