### ISSUE TITLE
konsola błąd

### ISSUE THREAD

**Issue by zorro8003PL** [Thefilippop1PL/Bazzars#12]
Czasami jak się wchodzi na serwer to pokazuje się taki błąd w konsoli:
http://scr.hu/19xy/qm7vw
Wersja pluginu: najnowsza
Silnik: spigot 1.7.10

**Comment by Thefilippop1PL** [comment]
Czasami się tak pokazuje, czy zawsze po wejściu? (tak, wiem napisales czasami, ale wole sie upewnic)

**Comment by zorro8003PL** [comment]
Czasami.

**Comment by Thefilippop1PL** [comment]
Naprawie w nastepnym update.

**Comment by TheMolkaPL** [comment]
Screenshot nie jest dostępny :cry:
