### ISSUE TITLE
MySql

### ISSUE THREAD

**Issue by ZielonyKapturnik** [Thefilippop1PL/Bazzars#5]
Zapis ofert w Mysql aby ciągle nie dodawać po wejściu na serwer

**Comment by Thefilippop1PL** [comment]
Najpierw trzeba popoprawiać wszystkie bugi ;p W przyszłości można coś takiego zrobić ;)

**Comment by TheMolkaPL** [comment]
Można już o tym pomyśleć :cake:

**Comment by kepo70** [comment]
A kiedy te błędy będą już naprawione na 100% ?

**Comment by TheMolkaPL** [comment]
@kepo70 które błędy? Jeżeli je znajdziesz to zgłoś je w [nowym issue](https://github.com/Thefilippop1PL/Bazzars/issues/new).

**Comment by kepo70** [comment]
Zacznę je testować za tydzien ;)

**Comment by kepo70** [comment]
Jeżeli coś znajdę napisze ;)

**Comment by Thefilippop1PL** [comment]
Myślę, że to nie jest potrzebne.
Druga rzecz - projekt jest aktualnie zawieszony.
