### ISSUE TITLE
Błędy przy dodowaniu itemu

### ISSUE THREAD

**Issue by kepo70** [Thefilippop1PL/Bazzars#6]
http://scr.hu/2m47/d9q82

**Comment by TheMolkaPL** [comment]
Podaj proszę log z konsoli w trakcie wykonywania tej komendy.

**Comment by Thefilippop1PL** [comment]
Podaj wersje pluginu i logi.

**Comment by TheMolkaPL** [comment]
Brak odpowiedzi ze strony autora. Prawdopodobny błąd z hologramami lub złą wersją serwera.
